# Generated by Django 5.1.6 on 2025-07-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_remove_book_like_delete_userbooklike'),
        ('Users', '0002_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_books',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='Books.book'),
        ),
    ]
