# Generated by Django 5.2.3 on 2025-07-21 02:54

import Books.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('cover', models.ImageField(blank=True, storage=Books.storage.GoogleDriveStorage, upload_to='cover_photo/')),
                ('genre', models.CharField(max_length=255)),
                ('document', models.FileField(blank=True, storage=Books.storage.GoogleDriveStorage, upload_to='book_pdf/')),
                ('like', models.BooleanField(default=False)),
                ('number_of_likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
            ],
            options={
                'verbose_name': 'User Book Like',
                'verbose_name_plural': 'User Book Likes',
            },
        ),
    ]
