# Generated by Django 5.1.6 on 2025-07-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_bookreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default='Book Summary'),
        ),
    ]
