# Generated by Django 5.1.6 on 2025-07-23 17:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_book_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
