# Generated by Django 5.1.6 on 2025-07-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
