# Generated by Django 5.1.6 on 2025-08-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_remove_book_like_delete_userbooklike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, to='Books.genre'),
        ),
    ]
